server:
  port: 8342
  
spring:
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 10s
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.rookie.entity.database"
      acks: 1
      retries: 3
    consumer:
      group-id: sync-cache
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
    
  application:
      name: business-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true
        ephemeral: true

mybatis-flex:
  datasource:
    reader:
      type: druid
      url: jdbc:mysql://localhost:33062/testdb
      username: root
      password: 12345
      asyncInt: true
    writer:
      type: druid
      url: jdbc:mysql://localhost:33061/testdb
      username: root
      password: 12345
      asyncInt: true
sa-token:
  token-name: fc-token
  timeout: 86400           # Token 有效期，单位秒 (默认30天，这里设为1天)
  active-timeout: -1       # Token 最低活跃度，单位秒 (默认-1，表示永不失效，只有到期才失效)
  is-concurrent: true      # 是否允许同一账号多端同时登录 (如果为false，后面登录会踢掉前面登录的)
  is-share-same-token: true # 是否在多端登录时共享同一 Token (通常与is-concurrent配合)
  is-read-body: true       # 是否从请求体获取 Token
  is-read-header: true     # 是否从请求头获取 Token
  is-read-cookie: true    #从cookie进行无感鉴权

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
